import { IconType } from "react-icons";
import { BsChatDots, BsCodeSlash, BsGear, BsGoogle, BsMarkdown, BsMoon } from "react-icons/bs";
import { SiBootstrap, SiFirebase, SiGooglegemini, SiMarkdown, SiNextdotjs, SiReact, SiTypescript } from "react-icons/si";

export const APP_NAME = "Gemini AI Chatbot";

export interface AboutPageContent {
    title: string;
    description: string;
    features: {
        Icon: IconType,
        title: string,
        description: string;
    }[];
    technologies: {
        Icon: IconType,
        title: string
    }[];
}

export const ABOUT_PAGE_CONTENT: AboutPageContent = {
    title: `Welcome to ${APP_NAME}!`,
    description: "Free Open Source AI Chatbot App integrated with Gemini.",
    features: [
        {
            Icon: BsGoogle,
            title: "Google Sign In",
            description: "Sign in using Google Account to use the app for free. This is needed to prevent abusing app API routes by malicious users."
        },
        {
            Icon: BsChatDots,
            title: "Text-based Temporary Chat Streaming",
            description: "Your chat is temporary, so it's not stored in database. AI provides streaming responses to deliver content as soon as possible."
        },
        {
            Icon: BsGear,
            title: "System Instruction (Context)",
            description: "Provide system instruction, also known as context, to get more tailored responses."
        },
        {
            Icon: BsMarkdown,
            title: "Markdown Support",
            description: "Gemini AI responses using Markdown syntax, so the app implements Markdown renderer to style the responses."
        },
        {
            Icon: BsCodeSlash,
            title: "Code highlighting",
            description: "Code generated by AI is highlighted for better user experience & convenience."
        },
        {
            Icon: BsMoon,
            title: "Dark mode",
            description: "Dark mode is the default (and only) app's theme."
        },
    ],
    technologies: [
        {
            Icon: SiNextdotjs,
            title: "Next.js 15+",
        },
        {
            Icon: SiReact,
            title: "React 19+",
        },
        {
            Icon: SiGooglegemini,
            title: "Gemini 2.0 Flash",
        },
        {
            Icon: SiFirebase,
            title: "Firebase 11+",
        },
        {
            Icon: SiTypescript,
            title: "TypeScript 5+",
        },
        {
            Icon: SiBootstrap,
            title: "Bootstrap 5.3+",
        },
        {
            Icon: SiMarkdown,
            title: "Markdown",
        },
    ]
}